// Generated by the build harness: WHITEHOLE_SOURCE_DIR as a string literal.
// Command-line -D quoting is unreliable across PowerShell/response-file layers,
// so the path is baked into a header the test TU includes instead.
#pragma once
#define WHITEHOLE_SOURCE_DIR "C:/Users/conta/OneDrive/Documents/GitHub/Whitehole-Pro"